export const PLACEHOLDERS = [
  "Search for 'Ocean waves' or 'Retro vibes'",
  "Explore 'Autumn tones' or 'Spring bloom'",
  "Find palettes for 'Website UI' or 'Interior decor'",
  "Look up 'Forest greens' or 'Mountain mist'",
  "Try 'Calm blues' or 'Energetic reds'",
  "Search for 'Japanese zen' or 'Tropical vibes'",
  "Type 'Christmas cheer' or 'Halloween spooky'",
  "Look for 'Wedding whites' or 'Birthday fun'",
  "Discover palettes inspired by 'Desert sunsets'",
  "Start with 'Soft pink' or 'Deep navy'",
  "Search for 'Vintage tones' or 'Futuristic neon'",
  "Explore 'Golden hour' or 'Lunar glow'",
  "Find 'Candy shop' or 'Stormy skies'",
  "Type 'Peach sorbet' or 'Velvet night'",
  "Look up 'Rainbow magic' or 'Chocolate delight'",
];
